### ISSUE TITLE
`sample_rate` not working correctly

### ISSUE THREAD

**Issue by ryan-keswick** [honeycombio/terraform-aws-integrations#40]
using the `logs_from_a_bucket_integrations` terraform module, I'm sending alb logs to `honeycomb.io`. however setting a `sample_rate = 10` is not having the desired effect of sending only 1/10 of the logs.

```
module "logs_from_a_bucket_integrations" {
  for_each          = local.load_balancers
  source            = "honeycombio/integrations/aws//modules/s3-logfile"
  name              = "${var.infra_prefix}-${each.key}-alb-logs-to-honeycomb"
  environment       = var.infra_prefix
  parser_type       = "alb"
  s3_bucket_arn     = aws_s3_bucket.access_logs[each.key].arn
  sample_rate       = 10
  honeycomb_api_key = jsondecode(data.aws_secretsmanager_secret_version.honeycomb_secret.secret_string)["honeycombTeam"]
  honeycomb_dataset = "${each.key}-access-logs"
}
```

**Comment by jharley** [comment]
@ryan-keswick thanks for the report!

How have you determined that it's not sending 10% of the logs? With a Usage Mode query?

**Comment by ryan-keswick** [comment]
@jharley I just want to clarify, the sampled logs don't contribute to `Billable Ingested Events`

**Comment by jharley** [comment]
> I just want to clarify, the sampled logs don't contribute to `Billable Ingested Events`

If I catch your meaning correctly: you're asking if the target ~90% unsent log events count against your Honeycomb ingestion amount? They do not as they never leave AWS.
