### ISSUE TITLE
incompatibility with aws 5.x provider

### ISSUE THREAD

**Issue by DavidS-om** [honeycombio/terraform-aws-integrations#48]
https://github.com/honeycombio/terraform-aws-integrations/blob/b846c4defc32d1908ec13944514b669541c940f3/modules/kinesis-firehose-honeycomb/main.tf#L18-L25

fails with the new 5.x aws provider from hashi:

> resource/aws_kinesis_firehose_delivery_stream: Remove s3_configuration attribute from the root of the resource. s3_configuration is now a part of the following blocks: elasticsearch_configuration, opensearch_configuration, redshift_configuration, splunk_configuration, and http_endpoint_configuration (https://github.com/hashicorp/terraform-provider-aws/issues/31138)

**Comment by jharley** [comment]
Fix for this was just released in `v1.0.0`
